### ISSUE TITLE
python setup.py install error

### ISSUE THREAD

**Issue by Sa-Hf** [Nanguage/DLO-HiC-Tools#7]
Hello,
Thanks for your wonderfull tool! I met with the following error during the installation process.How do I fix this.Thank you very much.
##my code
conda create -n dlohic2 python=3.9
conda activate dlohic2
conda install --yes numpy scipy matplotlib pandas cython h5py jsonschema graphviz
conda install -c bioconda --yes coreutils bwa samtools mafft pairix tabix cooler pysam java-jdk
conda install -c conda-forge --yes bzip2
git clone https://github.com/Nanguage/DLO-HiC-Tools.git
cd DLO-HiC-Tools/
python setup.py install

###error information
###
Traceback (most recent call last):.
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2239, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions
    self.stats = [stat.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>
    self.stats = [stat.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6268, in analyse_expressions
    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6268, in <listcomp>
    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6334, in analyse_expressions
    self.body = self.body.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions
    self.stats = [stat.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>
    self.stats = [stat.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6705, in analyse_expressions
    self.item = self.item.coerce_to(self.target.type, env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to
    src = PyTypeTestNode(src, dst_type, env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 13022, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"
AssertionError: PyTypeTest on non extension type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-b1ryd0fz/datrie-0.8.2/setup.py", line 39, in <module>
    
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1233, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2234, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
Cython.Compiler.Errors.CompilerCrash: 
Error compiling Cython file:
------------------------------------------------------------
...

    def __dealloc__(self):
        if self._c_trie is not NULL:
            cdatrie.trie_free(self._c_trie)

    def update(self, other=(), **kwargs):
   ^
------------------------------------------------------------

src/datrie.pyx:77:4: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(datrie.pyx:6:0)
StatListNode.stats[12] = StatListNode(datrie.pyx:37:5)
StatListNode.stats[0] = CClassDefNode(datrie.pyx:37:5,
    as_name = 'BaseTrie',
    class_name = 'BaseTrie',
    doc = "\n    Wrapper for libdatrie's trie.\n\n    Keys are unicode strings, values are integers -2147483648 <= x <= 2147483647.\n    ",
    module_name = '',
    visibility = 'private')
CClassDefNode.body = StatListNode(datrie.pyx:38:4)
StatListNode.stats[2] = DefNode(datrie.pyx:77:4,
    modifiers = [...]/0,
    name = 'update',
    np_args_idx = [...]/0,
    num_required_args = 1,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2239, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions
    self.stats = [stat.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>
    self.stats = [stat.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6268, in analyse_expressions
    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6268, in <listcomp>
    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6334, in analyse_expressions
    self.body = self.body.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions
    self.stats = [stat.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>
    self.stats = [stat.analyse_expressions(env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6705, in analyse_expressions
    self.item = self.item.coerce_to(self.target.type, env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to
    src = PyTypeTestNode(src, dst_type, env)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 13022, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"
AssertionError: PyTypeTest on non extension type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ywzhang/soft/DLO_Hic/DLO-HiC-Tools/setup.py", line 54, in <module>
    setup(
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/install.py", line 131, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 420, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 662, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 709, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 754, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 789, in resolve
    dist = best[req.key] = env.best_match(
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1087, in obtain
    return installer(requirement)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 900, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1174, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 262, in run_setup
    raise
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-b1ryd0fz/datrie-0.8.2/setup.py", line 39, in <module>
    
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1233, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 302, in Cython.Compiler.Visitor.CythonTransform.__call__
  File "Cython/Compiler/Visitor.py", line 284, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2234, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 251, in Cython.Compiler.Visitor.VisitorTransform.visitchildren
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/tmp/easy_install-b1ryd0fz/datrie-0.8.2/src/datrie.pyx>, 77, 4), 'AnalyseExpressionsTransform', 'Compiler crash in AnalyseExpressionsTransform\n\nModuleNode.body = StatListNode(datrie.pyx:6:0)\nStatListNode.stats[12] = StatListNode(datrie.pyx:37:5)\nStatListNode.stats[0] = CClassDefNode(datrie.pyx:37:5,\n    as_name = \'BaseTrie\',\n    class_name = \'BaseTrie\',\n    doc = "\\n    Wrapper for libdatrie\'s trie.\\n\\n    Keys are unicode strings, values are integers -2147483648 <= x <= 2147483647.\\n    ",\n    module_name = \'\',\n    visibility = \'private\')\nCClassDefNode.body = StatListNode(datrie.pyx:38:4)\nStatListNode.stats[2] = DefNode(datrie.pyx:77:4,\n    modifiers = [...]/0,\n    name = \'update\',\n    np_args_idx = [...]/0,\n    num_required_args = 1,\n    outer_attrs = [...]/2,\n    py_wrapper_required = True,\n    reqd_kw_flags_cname = \'0\',\n    used = True)\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2239, in visit_FuncDefNode\n    node.body = node.body.analyse_expressions(node.local_scope)\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions\n    self.stats = [stat.analyse_expressions(env)\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>\n    self.stats = [stat.analyse_expressions(env)\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6268, in analyse_expressions\n    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6268, in <listcomp>\n    self.if_clauses = [if_clause.analyse_expressions(env) for if_clause in self.if_clauses]\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6334, in analyse_expressions\n    self.body = self.body.analyse_expressions(env)\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in analyse_expressions\n    self.stats = [stat.analyse_expressions(env)\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 435, in <listcomp>\n    self.stats = [stat.analyse_expressions(env)\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6705, in analyse_expressions\n    self.item = self.item.coerce_to(self.target.type, env)\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 952, in coerce_to\n    src = PyTypeTestNode(src, dst_type, env)\n  File "/home/ywzhang/anaconda3/envs/dlohic2/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 13022, in __init__\n    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"\nAssertionError: PyTypeTest on non extension type', AssertionError('PyTypeTest on non extension type'), <traceback object at 0x7f1809f4b7c0>)
###

**Comment by Nanguage** [comment]
This has been solved, see the new install instructions in README.
